config/routes.rb
Rails.application.routes.draw do
  get 'user_sessions/new'
  get 'user_sessions/create'
  get 'user_sessions/destroy'
  get 'chat_rooms/show'

  root to: 'chat_rooms#index'

  resources :users, only: [:new, :create]
  resources :chat_rooms, only: [:new, :create, :show]
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :messages

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  attr_accessor :messages, :chat_rooms, :chat_room
  helper_method :messages, :chat_rooms, :chat_room

  def index
    @chat_rooms = ChatRoom.all
  end

  def show
    @chat_room = ChatRoom.find(params[:id])
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)

    respond_to do |format|
      if chat_room.save
        format.html { redirect_to root_path, notice: "#{chat_room.name} was created" }
      else
        format.html { render :new }
      end
    end
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:name], params[:password])

    if @user
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]

  attr_accessor :user
  helper_method :user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_rooms/_chat_room.html.erb
<div class="chat-room-link">
  <%= link_to chat_room.name, chat_room_path(chat_room), data: {turbolinks: "false"} %>
</div>

app/views/chat_rooms/_form.html.erb
<%= form_with model: chat_room, local: true do |f| %>
  <div class="field">
     <%= f.label :name %><br />
     <%= f.text_field :name %>
  </div>

  <%= f.submit %>
<% end %>

app/views/chat_rooms/index.html.erb
<%= link_to "New Chat Room", new_chat_room_path %>

<h2>Chat Rooms</h2>

<div id="chat_rooms">
  <%= render chat_rooms %>
</div>

app/views/chat_rooms/new.html.erb
<h2>New Chat Room</h2>

<%= render 'form' %>

app/views/chat_rooms/show.html.erb
<%= link_to 'Back to Chat Rooms', root_path %>

<h2><%= chat_room.name %></h2>

<div class="messages" id=<%= "messages-#{chat_room.id}" %>>
  <%= render chat_room.messages.order(created_at: :desc) %>
</div>

<input type="hidden" id="chat-room-id" value=<%= chat_room.id %>>

<input type="text" data-behavior="chat_room_speaker" id="chat_room_speaker" placeholder="Press Enter key to send" size="95">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="nav">
      <% if current_user %>
        <%= link_to "Logout", :logout, method: :post %>
      <% else %>
        <%= link_to "Register", new_user_path %> |
        <%= link_to "Login", :login %>
      <% end %>
    </div>
    <div>
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <div class="message-body">
    <%= "#{message.user.name}: #{message.body}" %>
  </div>

  <div class="message-time">
    <%= message.created_at.in_time_zone("America/Toronto")
      .strftime("%B %-d, %Y - %-l:%M %p") %>
  </div>
</div>

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <%= f.hidden_field :remember, value: true %>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>
  <div class="field">
     <%= f.label :name %><br />
     <%= f.text_field :name %>
  </div>
  <div class="field">
     <%= f.label :password %><br />
     <%= f.password_field :password %>
  </div>
  <div class="field">
     <%= f.label :password_confirmation %><br />
     <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>